port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: jagoanssh-Kaleaaa
    server: io.ruangguru.com
    port: 443
    type: vless
    uuid: 99df898a-07f5-4c2d-8dfb-0d9e3625ddd2
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id1vless.ipservers.xyz
    network: ws
    ws-opts:
      path: /jagoanssh
      headers:
        Host: id1vless.ipservers.xyz
    udp: true
  - name: jagoanssh-Kaleaaaa
    server: layanan.ruangguru.com
    port: 443
    type: vless
    uuid: f0ee0193-5cf0-4827-8ed5-7d5031bff8ec
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id2vless.ipservers.xyz
    network: ws
    ws-opts:
      path: /jagoanssh
      headers:
        Host: id2vless.ipservers.xyz
    udp: true
  - name: bug.com
    server: io.ruangguru.com
    port: 443
    type: trojan
    password: 9f5c2600-ba4c-11f0-8aff-1239d0255272
    skip-cert-verify: true
    sni: sg4.6n6.net
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg4.6n6.net
    udp: true
  - name: AKUN4
    server: 104.17.74.108
    port: 80
    type: vmess
    uuid: 2818be70-ba98-11f0-b238-205c6d5f5d78
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sg-1.hihu.net
    network: ws
    ws-opts:
      path: /rh0nm48e
      headers:
        Host: sg-1.hihu.net
    udp: true

proxy-groups:
  - name: ID-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - jagoanssh-Kaleaaa
      - jagoanssh-Kaleaaaa
      - bug.com
      - AKUN4

  - name: MIX-X
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - jagoanssh-Kaleaaa
      - jagoanssh-Kaleaaaa
      - bug.com
      - AKUN4
      
  - name: IKLAN
    type: select
    proxies:
     - MIX-X
     - REJECT

  - name: GAME
    type: select
    proxies:
     - ID-X
     - DIRECT
     - REJECT

rules:
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,Block,IKLAN
 - RULE-SET,Game,GAME
 - RULE-SET,Umum,MIX-X
 - RULE-SET,indo,ID-X
 - RULE-SET,Sosmed,MIX-X
 - RULE-SET,Streaming,MIX-X
 - RULE-SET,Bankid,ID-X
 - RULE-SET,Tiktok,MIX-X
 - RULE-SET,Meta,MIX-X
 - RULE-SET,PortGame,GAME
 - MATCH,MIX-X


rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./game.yaml 
  PortGame:
    type: file
    behavior: classical
    path: ./portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./umum.yaml 
  indo:
    type: file
    behavior: classical
    path: ./indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./meta.yaml
  Block:
    type: file
    behavior: domain
    path: ./block.yaml  




